VERSION_NAME=2.0.0

GROUP=com.oursprivacy
POM_ARTIFACT_ID=oursprivacy-android
POM_PACKAGING=aar

POM_NAME=OursPrivacy Android SDK
POM_DESCRIPTION=Official OursPrivacy tracking library for Android
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/with-ours/ours-privacy-android

POM_SCM_URL=https://github.com/with-ours/ours-privacy-android
POM_SCM_CONNECTION=scm:git:https://github.com/with-ours/ours-privacy-android.git
POM_SCM_DEV_CONNECTION=scm:git:git@github.com:with-ours/ours-privacy-android.git

POM_LICENSE_NAME=Apache License 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=oursprivacy
POM_DEVELOPER_NAME=Ours Privacy
POM_DEVELOPER_URL=https://oursprivacy.com
POM_DEVELOPER_EMAIL=support@oursprivacy.com

SONATYPE_HOST=CENTRAL_PORTAL
SONATYPE_AUTOMATIC_RELEASE=true
RELEASE_SIGNING_ENABLED=true

org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
