VERSION_NAME=8.0.3

POM_PACKAGING=aar
GROUP=com.oursprivacy.android

POM_DESCRIPTION=Official OursPrivacy tracking library for Android
POM_URL=https://github.com/oursprivacy/oursprivacy-android
POM_SCM_URL=https://github.com/oursprivacy/oursprivacy-android
POM_SCM_CONNECTION=scm:git:http://github.com/oursprivacy/oursprivacy-android
POM_SCM_DEV_CONNECTION=scm:git:git@github.com:oursprivacy/oursprivacy-android.git
POM_LICENCE_NAME=Apache License 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=oursprivacy_dev
POM_DEVELOPER_NAME=OursPrivacy Developers
POM_DEVELOPER_EMAIL=

RELEASE_REPOSITORY_URL=https://oss.sonatype.org/service/local/staging/deploy/maven2/
SNAPSHOT_REPOSITORY_URL=https://oss.sonatype.org/content/repositories/snapshots/

org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
