plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.maven.publish)
}

android {
    namespace "com.oursprivacy.android"
    enableKotlin = false
    compileSdk 36
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        warningsAsErrors false
        disable "UnusedResources"
        baseline = file("lint-baseline.xml")
    }

    defaultConfig {
        minSdk 23
        targetSdk 36
        buildFeatures.buildConfig = true
        consumerProguardFiles 'proguard.txt'

        buildConfigField "String", "OURSPRIVACY_VERSION", "\"${rootProject.property('VERSION_NAME')}\""

    }
    buildTypes {
        debug {
            minifyEnabled false
            testCoverageEnabled true
        }
        release {
            minifyEnabled false
        }
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
            returnDefaultValues = true
        }
    }

}

gradle.projectsEvaluated {
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation libs.annotation
    implementation libs.core
    testImplementation libs.junit
    testImplementation libs.robolectric
    testImplementation libs.androidx.test.core
    testImplementation libs.androidx.test.junit
    testImplementation libs.mockito.core
}
